# Permalinks
permalink:           pretty

# Setup
title:               Psychology
tagline:             welcome!
url:                 https://psyc.holo.gy
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt Hayden
  url:               https://github.com/Psychology-blog
  email:             hayden+github@morp.holo.gy

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/Psychology-blog/psychology-blog
google_analytics:
  id:                UA-102590217-6

# Gems
gems:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
